<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Sidebar */
/** @var SecureHtmlRenderer $secureRenderer */

use Magento\Checkout\Block\Cart\Sidebar;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

//cart icon
$icon_option   =  'athlete2_design/appearance_icons_header/header_icon_';
$cartIcon = $this->helper(Olegnax\Athlete2\Helper\Icons::class)->getIconHTML('cart', $icon_option); // $name, $icon_option = '', $classes = ''

$athlete       = $this->helper(Olegnax\Athlete2\Helper\Helper::class);
$cartBtnText   = $athlete->getConfig( 'athlete2_settings/header/minicart_btn_text' );

$hideText = false;
if($athlete->getConfig( 'athlete2_settings/header/minicart_btn_minimal' )){
    $hideText = !$athlete->getConfig( 'athlete2_settings/header/minicart_show_text' );
}

$moveSticky    = '';

if( $athlete->getConfig( 'athlete2_settings/header/header_layout' ) === 'header_1'){
	$moveSticky ='ox-move-sticky ox-move-sticky-header.main.right ox-move-item ox-move-item-header.main.right';
}
?>

